package com.tridenttech.domain;

// Generated Apr 5, 2015 2:38:37 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientInformation generated by hbm2java
 */
@Entity
@Table(name = "client_information", catalog = "ozuygqof_tamaar")
public class ClientInformation implements java.io.Serializable {

	private Integer clientInformationId;
	private String firstName;
	private String lastName;
	private String email;
	private String homePhoneNumber;
	private String mobilePhoneNumber;
	private String subject;
	private String message;
	private String gender;
	private Date date;
	private String sourceSite;

	public ClientInformation() {
	}

	public ClientInformation(String firstName, String lastName, String email,
			String homePhoneNumber, String mobilePhoneNumber, String subject,
			String message, String gender, Date date, String sourceSite) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.homePhoneNumber = homePhoneNumber;
		this.mobilePhoneNumber = mobilePhoneNumber;
		this.subject = subject;
		this.message = message;
		this.gender = gender;
		this.date = date;
		this.sourceSite = sourceSite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "client_information_id", unique = true, nullable = false)
	public Integer getClientInformationId() {
		return this.clientInformationId;
	}

	public void setClientInformationId(Integer clientInformationId) {
		this.clientInformationId = clientInformationId;
	}

	@Column(name = "first_name", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "home_phone_number", length = 15)
	public String getHomePhoneNumber() {
		return this.homePhoneNumber;
	}

	public void setHomePhoneNumber(String homePhoneNumber) {
		this.homePhoneNumber = homePhoneNumber;
	}

	@Column(name = "mobile_phone_number", length = 15)
	public String getMobilePhoneNumber() {
		return this.mobilePhoneNumber;
	}

	public void setMobilePhoneNumber(String mobilePhoneNumber) {
		this.mobilePhoneNumber = mobilePhoneNumber;
	}

	@Column(name = "subject", length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "message", length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "source_site", length = 45)
	public String getSourceSite() {
		return this.sourceSite;
	}

	public void setSourceSite(String sourceSite) {
		this.sourceSite = sourceSite;
	}

}
